# Jekyll configuration for GitHub Pages
# Theme configuration
theme: minima

# Site settings
title: "LLM Attacks - Comprehensive Security Vulnerability Database"
description: "A comprehensive database of Large Language Model (LLM) attack vectors and security vulnerabilities, including the latest 2025 research on agentic exploits, RAG attacks, and advanced ML security threats."
baseurl: "/LLM-Attacks"
url: "https://ai-security-research-group.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# GitHub Pages settings
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
